* ===========================================================================
* Test map geometry — generated by tools/gen_testmap.py, do not edit
* ===========================================================================
map.COLS  equ 24
map.ROWS  equ 8
