; ===========================================================================
; playfield.clearBlast — l'effacement du champ de jeu, a fenetre PILOTEE.
; ===========================================================================
; Le remplissage est un stack-blast PSHS A,B,DP,X,Y,U (9 octets/14 cycles,
; 1,556 cy/octet), ENTIEREMENT deroule, pleine largeur, qui descend du bas
; de la fenetre vers le haut. Deux parametres le pilotent, poses par
; playfield.clearWindow (SMC, la page est de la RAM-sur-cartouche) :
;
;   - l'operande du LDS   : OU commence la descente (la borne BASSE) ;
;   - l'operande du JMP   : ou l'on SAUTE dans le deroule — chaque poussee
;     zappee retire 9 octets en tete de descente, c'est la borne HAUTE.
;
; La fenetre maximale est lignes 11 a 178 : au-dessus (0-10) et en-dessous
; (191-199) c'est le masque ; la rangee de tuiles du bas (179-190) est
; TOUJOURS peinte par la tilemap (contrat sky_transparent.py). Le nombre de
; poussees est arrondi AU-DESSUS : le depassement (<= 8 octets) sort par la
; borne haute, dans des lignes que la tilemap repeint ou que le masque
; couvre — jamais sous $A000.
;
; La TIMELINE par stage (voir gen_clear_timeline.py et le tick dans
; stage-main.asm) ne stocke que les CHANGEMENTS de fenetre, precalcules :
; [camera(2), operande LDS plan couleur(2), offset de saut(2)]. Le plan
; forme se deduit (+$2000, meme offset).
;
; Pieges payes et graves ici (cf. l'historique du fichier) :
;   - AUCUN bsr/rts quand S est le pointeur d'ecriture (l'adresse de retour
;     se depile 7 000 octets plus bas, dans les zeros frais) ;
;   - CC est INPOUSSABLE sous IRQ ouvertes (l'IRQ materielle force E=1 dans
;     le CC qu'elle empile et le RTI restaure CE CC-la) — d'ou 9 octets ;
;   - S est legal comme pointeur : l'IRQ v2 bascule S en premiere
;     instruction, seul le push materiel touche la zone pas encore ecrite ;
;   - DP passe a zero (le moniteur pose le sien en tete d'IRQ).
;
; Fenetre par defaut (l'etat assemble) : lignes 11-178, 747 poussees.
; Cout : 21 093 cycles plein cadre ; chaque rangee de tuiles zappee par la
; timeline rend ~1 494 cycles.
; ===========================================================================

NPUSH    equ 747                       ; ceil(168 lignes x 40 / 9) — la fenetre max

playfield.clearBlast   EXPORT
playfield.clearWindow  EXPORT

 SECTION code

 OPT C,CT

playfield.clearBlast
        sts   >glb_register_s          ; meme convention que les sprites bdraw
        clra
        clrb
        tfr   a,dp                     ; DP=0 : il fait partie des octets pousses
        ldx   #0
        ldy   #0
        ldu   #0

clr.ldsA
        lds   #$A000+179*40            ; plan couleur — operande PILOTE (borne basse)
clr.jmpA
        jmp   clr.blockA               ; operande PILOTE (borne haute)
clr.blockA
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
clr.ldsB
        lds   #$C000+179*40            ; plan forme — pose par clearWindow (+$2000)
clr.jmpB
        jmp   clr.blockB
clr.blockB
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        lda   #dp/256                  ; DP moteur ($9F) — la page directe du jeu
        tfr   a,dp
        lds   >glb_register_s
        rts

; ---------------------------------------------------------------------------
; playfield.clearWindow - pose la fenetre d'effacement (les 4 operandes SMC).
;   in : Y = operande LDS du plan couleur ($A000 + (borne_basse+1)*40)
;        U = offset de saut dans le bloc deroule (2 x poussees zappees)
; Appele par paged.call aux changements de la timeline — jamais par trame.
; ---------------------------------------------------------------------------
playfield.clearWindow
        sty   >clr.ldsA+2
        tfr   y,d
        addd  #$2000
        std   >clr.ldsB+2
        tfr   u,d
        addd  #clr.blockA
        std   >clr.jmpA+1
        tfr   u,d
        addd  #clr.blockB
        std   >clr.jmpB+1
        rts

 ENDSECTION
