; ===========================================================================
; playfield.clearBlast — l'effacement du champ de jeu, version MAISON.
; ===========================================================================
; Pleine largeur (40 octets/ligne), lignes 9 a 178 des DEUX plans : 182 lignes
; x 40 = 7 280 octets par plan, moins la rangee de tuiles du bas — reste
; 170 lignes, 6 800 octets par plan : 755 poussees de 9 octets plus une de 5. Le
; debordement sur les lignes 9-10 (bande haute, repeinte par le masque en fin
; de trame) est ce qui fait tomber la division juste.
;
; La poussee : PSHS A,B,DP,X,Y,U = 9 octets en 14 cycles, 1,556 cy/octet —
; contre 1,975 pour la version generee (PSHU D,X,Y, champ strict).
;
; CC N'EST PAS DU LOT, et c'est un piege vecu : l'IRQ materielle force E=1
; dans le CC qu'elle empile, et le RTI restaure CE CC-la — apres la premiere
; IRQ tombee dans le blast (il dure plus d'une trame machine, une IRQ y tombe
; toujours), chaque poussee ecrivait $80 au lieu de $00 : colonnes rouges a
; l'ecran, une par lot, sur toute la fin du remplissage. Un andcc en tete de
; plan ne protege pas de ca.
;
; Les autres registres :
;   - S est le POINTEUR : la stack graphique est concue pour (meme geste que
;     les sprites bdraw v1) — l'IRQ v2 bascule S en premiere instruction,
;     seul le push materiel (12 octets) touche la zone SOUS S, pas encore
;     ecrite, que les poussees suivantes recouvrent ;
;   - DP passe a zero le temps du remplissage : le moniteur pose son propre
;     DP en tete d'IRQ (cf. engine/irq/Irq.asm, « set by the monitor »).
;
; TOUT EST EN LIGNE : zero branchement, zero compteur — et AUCUN bsr/rts
; interne : S etant le pointeur d'ecriture, une adresse de retour posee par
; bsr serait depilee 7 280 octets plus bas, dans les zeros fraichement
; ecrits (vecu aussi : PC=$0000, machine dans le decor).
;
; Appel : paged.call depuis la boucle de trame, en tete de verrou graphique.
; Clobbe tout, restaure S et DP. 21 215 cycles, 1,56 cy/octet.
; ===========================================================================

ROWTOP   equ 9*40                      ; 360  — debut ligne 9
ROWEND   equ 179*40                    ; 7160 — fin de la ligne 178 : la rangee
                                       ; de tuiles du bas (179-190) est TOUJOURS
                                       ; peinte par la tilemap (in.png ajuste),
                                       ; l'effacer serait payer deux fois
NPUSH    equ (ROWEND-ROWTOP-5)/9       ; 755 poussees de 9, puis une de 5

playfield.clearBlast EXPORT

 SECTION code

 OPT C,CT

playfield.clearBlast
        sts   >glb_register_s          ; meme convention que les sprites bdraw
        clra
        clrb
        tfr   a,dp                     ; DP=0 : il fait partie des octets pousses
        ldx   #0
        ldy   #0
        ldu   #0

        lds   #$A000+ROWEND            ; plan couleur
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x                 ; le reliquat : 5 octets

        lds   #$C000+ROWEND            ; plan forme
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x                 ; le reliquat : 5 octets

        lda   #dp/256                  ; DP moteur ($9F) — la page directe du jeu
        tfr   a,dp
        lds   >glb_register_s
        rts

 ENDSECTION
