; GENERE par tools/gen_warship_flames.py — les tranches des gerbes, resolues au chargement.
set_fl_d_0  EXTERNAL
set_fl_d_1  EXTERNAL
set_fl_d_2  EXTERNAL
set_fl_d_3  EXTERNAL
set_fl_d_4  EXTERNAL
set_fl_d_5  EXTERNAL
set_fl_d_6  EXTERNAL
set_fl_d_7  EXTERNAL
set_fl_d_8  EXTERNAL
set_fl_d_9  EXTERNAL
set_fl_d_10  EXTERNAL
set_fl_d_11  EXTERNAL
set_fl_d_12  EXTERNAL
set_fl_d_13  EXTERNAL
set_fl_d_14  EXTERNAL
set_fl_d_15  EXTERNAL
set_fl_r_0  EXTERNAL
set_fl_r_1  EXTERNAL
set_fl_r_2  EXTERNAL
set_fl_r_3  EXTERNAL
set_fl_r_4  EXTERNAL
set_fl_r_5  EXTERNAL
set_fl_r_6  EXTERNAL
set_fl_r_7  EXTERNAL
set_fl_r_8  EXTERNAL
set_fl_r_9  EXTERNAL
set_fl_r_10  EXTERNAL
set_fl_r_11  EXTERNAL
set_fl_r_12  EXTERNAL
set_fl_r_13  EXTERNAL
set_fl_r_14  EXTERNAL
set_fl_r_15  EXTERNAL
set_fl_r_16  EXTERNAL
set_fl_r_17  EXTERNAL
set_fl_r_18  EXTERNAL
set_fl_r_19  EXTERNAL
set_fl_r_20  EXTERNAL
set_fl_r_21  EXTERNAL
set_fl_r_22  EXTERNAL
set_fl_r_23  EXTERNAL
set_fl_r_24  EXTERNAL
set_fl_r_25  EXTERNAL
set_fl_r_26  EXTERNAL
set_fl_r_27  EXTERNAL
set_fl_r_28  EXTERNAL
set_fl_r_29  EXTERNAL
set_fl_r_30  EXTERNAL
set_fl_l_0  EXTERNAL
set_fl_l_1  EXTERNAL
set_fl_l_2  EXTERNAL
set_fl_l_3  EXTERNAL
set_fl_l_4  EXTERNAL
set_fl_l_5  EXTERNAL
set_fl_l_6  EXTERNAL
set_fl_l_7  EXTERNAL
set_fl_l_8  EXTERNAL
set_fl_l_9  EXTERNAL
set_fl_l_10  EXTERNAL
set_fl_l_11  EXTERNAL
set_fl_l_12  EXTERNAL
set_fl_l_13  EXTERNAL
set_fl_l_14  EXTERNAL
set_fl_l_15  EXTERNAL
set_fl_l_16  EXTERNAL
set_fl_l_17  EXTERNAL
set_fl_l_18  EXTERNAL
set_fl_l_19  EXTERNAL
set_fl_l_20  EXTERNAL
set_fl_l_21  EXTERNAL
set_fl_l_22  EXTERNAL
set_fl_l_23  EXTERNAL
set_fl_l_24  EXTERNAL
set_fl_l_25  EXTERNAL
set_fl_l_26  EXTERNAL
set_fl_l_27  EXTERNAL
set_fl_l_28  EXTERNAL
set_fl_p_0  EXTERNAL
set_fl_p_1  EXTERNAL
set_fl_p_2  EXTERNAL
set_fl_p_3  EXTERNAL
set_fl_p_4  EXTERNAL
set_fl_p_5  EXTERNAL
set_fl_p_6  EXTERNAL
set_fl_p_7  EXTERNAL
