package com.widedot.m6809.gamebuilder.plugin.objectindex;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.configuration2.tree.ImmutableNode;

import com.widedot.m6809.gamebuilder.spi.BuildContext;
import com.widedot.m6809.gamebuilder.spi.configuration.Attribute;
import com.widedot.m6809.util.FileUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * The object index a stage exports to the resident engine : the id equates
 * (ObjID_*) and the five tables RunObjects and the sprite runtime consult —
 * Obj_Index_Page/Address, Ani_Page_Index, Ani_Asd_Index, Img_Page_Index.
 *
 * One declared entry per object id, in id order : the id space is what the
 * wave data assembles against, so it is authored here, never derived. An
 * entry names its page source (a file or region whose .page equate the
 * layout publishes) and its entry symbol ; an enemy not ported yet is
 * declared against the stage's stub object, and that line simply goes away
 * when the enemy lands — the transition lives in the declarations, not in
 * this emitter (docs/lang/fr/plan-migration-cible-2026-08.md, phase 1).
 *
 * First application of the index emitter of the target model
 * (docs/lang/fr/analyse-placement-2026-08.md §10, §16) : the parallel
 * layout, entry 0 reserved, the window bits carried by the page byte.
 */
@Slf4j
public class ObjectIndexPlugin {

	public static void run(ImmutableNode node, BuildContext ctx) throws Exception {

		String name = Attribute.getString(node, ctx, "name");
		String genconst = Attribute.getString(node, ctx, "genconst");
		String gensource = Attribute.getString(node, ctx, "gensource");
		// what fills slot 0 of the Ani/Img page tables : the region holding
		// the index itself — a mounted read of the reserved slot must land on
		// RAM that exists
		String zero = Attribute.getString(node, ctx, "zero");
		String guard = Attribute.getString(node, ctx, "guard",
				"OBJID_CONST_" + name.toUpperCase().replaceAll("[^A-Z0-9]", "_"));

		List<String[]> entries = new ArrayList<String[]>();   // {objid, pagefile, symbol, asd}
		for (ImmutableNode child : node.getChildren()) {
			if (!"entry".equals(child.getNodeName())) {
				throw new Exception(ctx.sources.locate(child) + ": <objectindex> only contains"
						+ " <entry> elements, found <" + child.getNodeName() + ">");
			}
			entries.add(new String[] {
					Attribute.getString(child, ctx, "name"),
					Attribute.getString(child, ctx, "file"),
					Attribute.getString(child, ctx, "object"),
					Attribute.getString(child, ctx, "asd", "Ani_Asd_none") });
		}
		if (entries.isEmpty()) {
			throw new Exception("objectindex '" + name + "' declares no entry");
		}

		String nl = System.lineSeparator();

		// --- the id equates -----------------------------------------------
		StringBuilder c = new StringBuilder();
		c.append("* Object ids of ").append(name)
		 .append(" - generated by <objectindex>, do not edit").append(nl).append(nl);
		c.append(" IFNDEF ").append(guard).append(nl);
		c.append(guard).append(" equ 1").append(nl).append(nl);
		int id = 0;
		for (String[] e : entries) {
			id++;
			c.append(e[0]).append(" equ ").append(id).append(nl);
		}
		c.append("objid.count equ ").append(id).append(nl);
		for (String[] e : entries) {
			if (e[0].equals("ObjID_animation")) {
				c.append("objid.animation equ ObjID_animation").append(nl);
			}
		}
		c.append(nl).append(" ENDC").append(nl);
		write(ctx, genconst, c.toString());

		// --- the five tables ----------------------------------------------
		StringBuilder s = new StringBuilder();
		s.append("* Object index of ").append(name)
		 .append(" - generated by <objectindex>, do not edit").append(nl).append(nl);

		s.append("Obj_Index_Page").append(nl);
		s.append("        fcb   0 ; id 0 : reserved slot, never run").append(nl);
		for (String[] e : entries) {
			s.append("        fcb   map.RAM_OVER_CART+").append(e[1]).append(".page ; ")
			 .append(e[0]).append(nl);
		}
		s.append(nl).append("Obj_Index_Address").append(nl);
		s.append("        fdb   0").append(nl);
		for (String[] e : entries) {
			s.append("        fdb   ").append(e[2]).append(" ; ").append(e[0]).append(nl);
		}

		s.append(nl).append("Ani_Page_Index").append(nl);
		s.append("        fcb   map.RAM_OVER_CART+").append(zero).append(".page").append(nl);
		for (String[] e : entries) {
			s.append("        fcb   map.RAM_OVER_CART+").append(e[1]).append(".page ; ")
			 .append(e[0]).append(nl);
		}
		s.append(nl).append("Ani_Asd_Index").append(nl);
		s.append("        fdb   Ani_Asd_none").append(nl);
		for (String[] e : entries) {
			s.append("        fdb   ").append(e[3]).append(" ; ").append(e[0]).append(nl);
		}
		s.append(nl).append("Ani_Asd_none").append(nl);
		s.append("        fdb   0").append(nl);

		s.append(nl).append("Img_Page_Index").append(nl);
		s.append("        fcb   map.RAM_OVER_CART+").append(zero).append(".page").append(nl);
		for (String[] e : entries) {
			s.append("        fcb   map.RAM_OVER_CART+").append(e[1]).append(".page ; ")
			 .append(e[0]).append(nl);
		}
		write(ctx, gensource, s.toString());

		log.info("objectindex {} : {} entries", name, id);
	}

	private static void write(BuildContext ctx, String rel, String content) throws Exception {
		String path = ctx.path + File.separator + rel;
		Files.createDirectories(Paths.get(FileUtil.getDir(path)));
		Files.write(Paths.get(path), content.getBytes(StandardCharsets.UTF_8));
	}
}
