package com.widedot.m6809.gamebuilder.plugin.unit;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

import org.apache.commons.configuration2.tree.ImmutableNode;

import com.widedot.m6809.gamebuilder.Handlers;
import com.widedot.m6809.gamebuilder.plugin.lwasm.LwasmPlugin;
import com.widedot.m6809.gamebuilder.spi.BuildContext;
import com.widedot.m6809.gamebuilder.spi.configuration.Attribute;
import com.widedot.m6809.util.FileUtil;

/**
 * One indivisible object : an entry symbol and its content, code and images
 * alike. A unit is ITS OWN ASSEMBLY — the v1 sources all name their entry
 * {@code Object} and their tables {@code Routines}, so two of them in one
 * assembly collide, which is why v1 compiled every object separately. The
 * builder concatenates a unit's sources into one generated file and assembles
 * it alone ; the children keep their normal envelope — EXPORT, SECTION, entry
 * label — exactly as they would in a standalone {@code <file>}.
 *
 * Hosted by a {@code <file>}, the enclosing file itself stands for the
 * member : it IS the file a {@code <gfxcomp>} index would name.
 */
public class UnitPlugin {

	/** the object form : a unit hosted directly by a {@code <file>} */
	public static com.widedot.m6809.gamebuilder.spi.ObjectDataInterface unitObject(
			ImmutableNode node, BuildContext ctx) throws Exception {
		String host = ctx.staticLink.currentHost();
		String gendir = Attribute.getString(node, ctx, "gendir", "gen/units");
		String[] unit = unit(node, ctx, gendir, host != null ? host : "unit");
		return LwasmPlugin.getObject(lwasmOf(unit[0]), ctx);
	}

	/**
	 * The parts form : a unit is ONE element of a collection — the word that
	 * groups plugins whose output must stay continuous. The packer may cut
	 * between a unit and its neighbours, never inside it. The source written
	 * here carries the FILE name as its member placeholder ; when the packing
	 * lands the unit in a cut member, the emission regenerates it with the
	 * real member name (a nested genindex writes {@code <member>$PAGE}).
	 */
	public static java.util.List<String[]> getParts(ImmutableNode node, BuildContext ctx)
			throws Exception {
		String host = ctx.staticLink.currentHost();
		String gendir = Attribute.getString(node, ctx, "gendir", "gen/units");
		String[] unit = unit(node, ctx, gendir, host != null ? host : "unit");
		java.util.List<String[]> parts = new java.util.ArrayList<String[]>();
		parts.add(unit);
		return parts;
	}

	/** an lwasm node assembling one unit source alone, for the collection */
	public static ImmutableNode lwasmOfUnit(String source) {
		return lwasmOf(source);
	}

	/** write the unit's generated source ; returns {source path, entry symbol} */
	public static String[] unit(ImmutableNode node, BuildContext ctx, String gendir,
			String memberFile) throws Exception {

		String symbol = Attribute.getString(node, ctx, "symbol");
		String name = Attribute.getString(node, ctx, "name", symbol.replace('.', '_'));
		// two kinds of unit, told apart by the author : sources that open
		// their own section and export their own symbol are included as-is ;
		// bare data (a wave table, a text) gets the whole envelope written
		// for it — section, exported label, ends.
		String section = Attribute.getStringOpt(node, ctx, "section");

		StringBuilder out = new StringBuilder("* Generated by unit " + name
				+ System.lineSeparator());
		if (section != null) {
			// EXPORT stays outside the section, as everywhere else
			out.append(symbol).append(" EXPORT").append(System.lineSeparator())
			   .append(" section ").append(section).append(System.lineSeparator())
			   .append(symbol).append(System.lineSeparator());
		}
		BuildContext localCtx = ctx.child();
		String body = Attribute.getStringOpt(node, ctx, "body");
		if (body != null) {
			out.append("        INCLUDE \"").append(ctx.path).append(File.separator)
			   .append(body).append('"').append(System.lineSeparator());
		}
		for (ImmutableNode child : node.getChildren()) {
			String plugin = child.getNodeName();
			com.widedot.m6809.gamebuilder.spi.DefaultPluginInterface defaultHandler =
					Handlers.getDefault(plugin);
			com.widedot.m6809.gamebuilder.spi.FilePluginInterface fileHandler =
					Handlers.getFile(plugin);
			if (defaultHandler == null && fileHandler == null) {
				throw new Exception(ctx.sources.locate(child) + ": <" + plugin
						+ "> is not valid inside a <unit>");
			}
			// a gfxcomp's index references its images through <file>$PAGE :
			// inside a unit, that file is the entry this unit lands in, which
			// the author cannot know. The builder writes it.
			if ("gfxcomp".equals(plugin) && child.getAttributes().containsKey("genindex")) {
				ImmutableNode.Builder patched = new ImmutableNode.Builder();
				patched.name(child.getNodeName());
				for (java.util.Map.Entry<String, Object> a : child.getAttributes().entrySet()) {
					if (!"file".equals(a.getKey())) {
						patched.addAttribute(a.getKey(), a.getValue());
					}
				}
				patched.addAttribute("file", memberFile);
				for (ImmutableNode grandChild : child.getChildren()) {
					patched.addChild(grandChild);
				}
				child = patched.create();
			}
			if (defaultHandler != null) {
				defaultHandler.run(child, localCtx);
				ctx.publish(localCtx);
			}
			if (fileHandler != null) {
				out.append("        INCLUDE \"")
				   .append(fileHandler.getFile(child, localCtx).getPath())
				   .append('"').append(System.lineSeparator());
				ctx.publish(localCtx);
			}
		}

		if (section != null) {
			out.append(" endsection").append(System.lineSeparator());
		}
		String source = gendir + File.separator + name + ".unit.asm";
		Files.createDirectories(Paths.get(FileUtil.getDir(ctx.path + File.separator + source)));
		Files.write(Paths.get(ctx.path + File.separator + source),
				out.toString().getBytes(StandardCharsets.UTF_8));
		// relative : AsmPlugin prefixes ctx.path itself
		return new String[] { source, symbol };
	}

	/** an lwasm node assembling one source file on its own */
	private static ImmutableNode lwasmOf(String source) {
		ImmutableNode.Builder asm = new ImmutableNode.Builder();
		asm.name("asm").addAttribute("filename", source);
		ImmutableNode.Builder lwasm = new ImmutableNode.Builder();
		lwasm.name("lwasm").addAttribute("gensource", source + ".cat.asm")
			 .addChild(asm.create());
		return lwasm.create();
	}
}
