 IFNDEF loader.PAGE
loader.PAGE equ 4
 ENDC

 IFNDEF loader.ADDRESS
loader.ADDRESS equ $6000
 ENDC

 IFNDEF loader.DEFAULT_DYNAMIC_MEMORY_SIZE
loader.DEFAULT_DYNAMIC_MEMORY_SIZE equ loader.ADDRESS-loader.memoryPool+$4000
 ENDC

 IFNDEF loader.DEFAULT_SCENE_DIR_ID
loader.DEFAULT_SCENE_DIR_ID equ 0
 ENDC

 IFNDEF loader.DEFAULT_SCENE_FILE_ID
loader.DEFAULT_SCENE_FILE_ID equ 0
 ENDC

 IFNDEF loader.DEFAULT_SCENE_EXEC_PAGE
loader.DEFAULT_SCENE_EXEC_PAGE equ 5
 ENDC

 IFNDEF loader.DEFAULT_SCENE_EXEC_ADDR
loader.DEFAULT_SCENE_EXEC_ADDR equ $2100
 ENDC