package com.widedot.toolbox.graphics.gfxcomp;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.configuration2.tree.ImmutableNode;

import com.widedot.m6809.gamebuilder.spi.BuildContext;
import com.widedot.m6809.gamebuilder.spi.configuration.Attribute;
import com.widedot.toolbox.graphics.gfxcomp.imageset.ImageSet;
import com.widedot.toolbox.graphics.gfxcomp.setting.VideoMemory;
import com.widedot.toolbox.graphics.gfxcomp.transformer.mirror.Mirror;

import lombok.extern.slf4j.Slf4j;

/**
 * Handler for the &lt;gfxcomp&gt; element : compiles PNGs into 6809 code inside
 * a &lt;lwasm&gt; unit.
 *
 * The compiler produces one source per image variant plus the imageset index,
 * while a source unit is a single file, so what comes back is a generated file
 * of INCLUDE lines. The parts stay on disk under their own names, which is what
 * makes them comparable with the v1 generator's output (see bench/run.sh).
 *
 * Placement is left to the load time linker: the generated code carries no ORG,
 * and the index references it through the adr_/pge_ symbols the linker resolves.
 */
@Slf4j
public class GfxcompPlugin {

	public static File getFile(ImmutableNode node, BuildContext ctx) throws Exception {

		String gendir = ctx.path + File.separator + Attribute.getString(node, ctx, "gendir");
		String gensource = ctx.path + File.separator + Attribute.getString(node, ctx, "gensource");
		String genindex = Attribute.getStringOpt(node, ctx, "genindex");
		String file = Attribute.getStringOpt(node, ctx, "file");

		VideoMemory.memoryLinearBits = Attribute.getInteger(node, ctx, "linearbits", 4);
		VideoMemory.memoryPlanarBits = Attribute.getInteger(node, ctx, "planarbits", 8);
		VideoMemory.memoryLineBytes  = Attribute.getInteger(node, ctx, "linebytes", 40);
		VideoMemory.memoryNbPlanes   = Attribute.getInteger(node, ctx, "nbplanes", 2);

		if (genindex != null && file == null) {
			throw new Exception("<gfxcomp genindex> also needs file, the direntry name the images "
			                  + "end up in : the index references their page through <file>$PAGE");
		}
		ImageSet imageset = genindex == null ? null : new ImageSet(0, file);
		List<String> generated = new ArrayList<>();

		for (ImmutableNode child : node.getChildren()) {
			if (!"image".equals(child.getNodeName())) {
				throw new Exception("Element <" + child.getNodeName() + "> is not valid inside <gfxcomp>");
			}
			generated.addAll(compile(child, ctx, gendir, imageset));
		}

		if (generated.isEmpty()) {
			throw new Exception("no <image> to compile in <gfxcomp>");
		}

		if (imageset != null) {
			String index = ctx.path + File.separator + genindex;
			Files.createDirectories(Paths.get(index).getParent());
			imageset.generate(index);
			generated.add(index);
		}

		return writeIncludes(gensource, generated);
	}

	private static List<String> compile(ImmutableNode node, BuildContext ctx, String gendir, ImageSet imageset)
			throws Exception {

		String name = Attribute.getString(node, ctx, "name");
		String filename = ctx.path + File.separator + Attribute.getString(node, ctx, "filename");
		Integer index = Attribute.getIntegerOpt(node, ctx, "index");

		List<String> files = new ArrayList<>();
		for (ImmutableNode child : node.getChildren()) {
			if (!"encoder".equals(child.getNodeName())) {
				throw new Exception("Element <" + child.getNodeName() + "> is not valid inside <image>");
			}
			String encoder  = Attribute.getString(child, ctx, "name", Image.TYPE_DRAW);
			String mirror   = Attribute.getString(child, ctx, "mirror", Mirror.NONE);
			Integer shift   = Attribute.getInteger(child, ctx, "shift", 0);
			String position = Attribute.getString(child, ctx, "position", Image.POSITION_CENTER);

			Image image = new Image(name, index, filename, encoder, mirror, shift, position);
			image.encode(gendir);
			if (imageset != null) {
				imageset.addImage(image);
			}

			log.debug("gfxcomp compiled {} as {}", name, image.getVariant());
			files.add(gendir + File.separator + image.getFullName() + ".asm");
			String erase = gendir + File.separator + image.getFullName() + "_erase.asm";
			if (Files.exists(Paths.get(erase))) {
				files.add(erase);
			}
		}

		if (files.isEmpty()) {
			throw new Exception("image " + name + " has no <encoder>");
		}
		return files;
	}

	private static File writeIncludes(String gensource, List<String> files) throws Exception {
		// the compiled code carries no SECTION of its own : the unit owns it
		StringBuilder source = new StringBuilder("* Generated by gfxcomp" + System.lineSeparator());
		source.append(" SECTION code").append(System.lineSeparator());
		for (String file : files) {
			source.append("        INCLUDE \"").append(file).append('"').append(System.lineSeparator());
		}
		source.append(" ENDSECTION").append(System.lineSeparator());
		Path path = Paths.get(gensource);
		if (path.getParent() != null) {
			Files.createDirectories(path.getParent());
		}
		Files.writeString(path, source.toString());
		return path.toFile();
	}
}
