#!/usr/bin/env python3
"""examples/mscroll1 test pattern : a two-level 1 bpp map.

Geometry : 8192 x 1024 px — 512 x 64 blocks of 16x16, grouped in chunks of
8x8 blocks (128x128 px), a layout of 64 x 8 chunks. Wider than 4096 px on
purpose : block columns past 255 exercise the 16-bit column path.

Every block carries :
  - a horizontal ruler on its line 0 (continuous across the map : a one
    pixel vertical offset — the ribbon seam, a feed anchored wrong — shows
    as a step) ;
  - a dotted vertical ruler on its column 0 ;
  - a 45-degree hatch whose period is the block size (continuous too) ;
  - its own id, 8 bits as 2x2 squares in a 4x2 grid : a wrong block, a
    wrong chunk or a wrong layout lookup shows up as a different code.
256 distinct blocks, 32 chunks of pseudo-random blocks, a pseudo-random
layout of those chunks.

Outputs (assets/, committed — read by the build and by tools/check.py) :
  tiles.bin  the tileset, tile-major (16 big-endian words per block, bit 7
             of the first byte = leftmost pixel), 8 KB : loaded at offset
             $2000 of its page, the half the data window shows at $A000
  map.bin    the layout (one chunk index per byte, row-major) then the
             chunk table (128 bytes per chunk : 8 rows of 8 block ids,
             big-endian words, premultiplied by 32)
  mire.equ   the geometry equates the game mode includes
  mire.png   an overview (1/4 scale), for humans

usage : python3 tools/gen_mire.py   (from examples/mscroll1)
"""
import os

BLOCKS = 256
CHUNKS = 32
LAYOUT_W, LAYOUT_H = 64, 8
MAP_W, MAP_H = LAYOUT_W * 128, LAYOUT_H * 128

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUT = os.path.join(ROOT, 'assets')


def block_pixel(b, x, y):
    """Ink (True) at (x, y) of block b."""
    if y == 0:
        return True
    if x == 0:
        return y % 2 == 0
    if (x - y) % 16 == 8:
        return True
    if 4 <= x < 12 and 6 <= y < 10:
        k = (x - 4) // 2 + 4 * ((y - 6) // 2)
        return bool((b >> k) & 1)
    return False


def chunk_block(c, i, j):
    """Block id at row i, column j of chunk c."""
    return (c * 37 + i * 11 + j * 5 + i * j * 3) & 255


def layout_chunk(col, row):
    return (col * 7 + row * 13 + col * row) % CHUNKS


def map_pixel(x, y):
    x %= MAP_W
    y %= MAP_H
    c = layout_chunk(x >> 7, y >> 7)
    b = chunk_block(c, (y >> 4) & 7, (x >> 4) & 7)
    return block_pixel(b, x & 15, y & 15)


def block_bytes(b):
    out = bytearray()
    for y in range(16):
        v = 0
        for x in range(16):
            v = (v << 1) | block_pixel(b, x, y)
        out += v.to_bytes(2, 'big')
    return bytes(out)


def main():
    os.makedirs(OUT, exist_ok=True)
    tiles = b''.join(block_bytes(b) for b in range(BLOCKS))
    layout = bytes(layout_chunk(c, r) for r in range(LAYOUT_H) for c in range(LAYOUT_W))
    chunks = bytearray()
    for c in range(CHUNKS):
        for i in range(8):
            for j in range(8):
                chunks += (chunk_block(c, i, j) * 32).to_bytes(2, 'big')
    with open(os.path.join(OUT, 'tiles.bin'), 'wb') as f:
        f.write(tiles)
    with open(os.path.join(OUT, 'map.bin'), 'wb') as f:
        f.write(layout + chunks)
    with open(os.path.join(OUT, 'mire.equ'), 'w') as f:
        f.write('; generated by tools/gen_mire.py\n')
        f.write('mire.MAP_WIDTH      equ %d\n' % MAP_W)
        f.write('mire.MAP_HEIGHT     equ %d\n' % MAP_H)
        f.write('mire.LAYOUT_STRIDE  equ %d\n' % LAYOUT_W)
        f.write('mire.CHUNKS_OFFSET  equ %d\n' % len(layout))
    try:
        from PIL import Image
        img = Image.new('1', (MAP_W // 4, MAP_H // 4))
        px = img.load()
        for y in range(MAP_H // 4):
            for x in range(MAP_W // 4):
                px[x, y] = map_pixel(x * 4, y * 4)
        img.save(os.path.join(OUT, 'mire.png'))
    except ImportError:
        pass
    print('tiles %d B, map %d B (layout %d + chunks %d)'
          % (len(tiles), len(layout) + len(chunks), len(layout), len(chunks)))


if __name__ == '__main__':
    main()
