* ---------------------------------------------------------------------------
* Horizontal scroll over a SPARSE COLUMN map (2026-09-06)
* ------------------------------------------------------
*
* The alternative to scroll-map-buffered-even.asm, which walks the whole
* screen rectangle of a dense map and spends most of its time skipping empty
* cells (measured on r-type stage 1 : 150 of 195 cells empty, ~4 300 cycles
* of skips per loop). Here the map is a table of COLUMNS, each column a list
* of its FULL cells only — nothing empty is ever visited.
*
* The table (generated by <tilecols>, baked in a .static section) :
*
*     label       fdb   col0, col1, ...     one word per map column
*     col0        fcb   page                a full cell : page of the tile (+$60)
*                 fdb   address             its compiled routine
*                 fdb   offset              video offset of its row (row x tile
*                                           height x 40), precomputed
*                 ...
*                 fcb   0                   end of column (page 0 never exists)
*
* The three tile bytes come first and in the dense map's order, so a
* rectangle patch writes them the same way (see tilemap.patch.cols) — a
* column an animation touches is generated DENSE (all rows present, empty
* ones pointing tilemap.null), which gives its cells a fixed address.
*
* ScrollCols is Scroll with the map step of a column table (2 bytes instead of
* rows x 3) ; DrawTilesCols replaces DrawTiles. The private variables, the
* parameters and InitScroll are shared with the dense engine, which must be
* assembled in the same unit.
* ---------------------------------------------------------------------------
tilemap.null
        rts                            ; the empty cell of a dense column

ScrollCols
        ldd   glb_camera_x_pos
        std   glb_camera_x_pos_old
        clr   glb_camera_move
        ldx   scroll_max
        cmpx  buffer_x_pos
        bne   >
        cmpx  buffer_x_pos+2
        bne   >
        rts
!
        ldb   scroll_vel
        sex
        sta   @a
        lda   gfxlock.frameDrop.count
        sta   glb_d0_b
        bne   @loop1
        inc   glb_d0_b
@loop1
        ldd   glb_camera_x_pos+1
        addd  scroll_vel
        std   glb_camera_x_pos+1
        lda   glb_camera_x_pos
        adca  #$00
@a      equ   *-1
        sta   glb_camera_x_pos
        dec   glb_d0_b
        bne   @loop1
;
        lda   gfxlock.backBuffer.id
        asla
        ldu   #buffer_x_pos
        ldx   glb_camera_x_pos
        cmpx  a,u
        beq   @rts
        cmpx  scroll_max
        ble   >
        ldx   scroll_max
        stx   glb_camera_x_pos
!       stx   a,u
;
        lda   #1
        sta   <glb_force_sprite_refresh
        sta   glb_camera_move
;
        ldb   glb_camera_x_pos+1
        lsrb
        bcs   @odd
@even   lda   scroll_map_page_even
        ldx   scroll_map_even
        bra   >
@odd    lda   scroll_map_page_odd
        ldx   scroll_map_odd
!       sta   tile_buffer_page
        stx   tile_buffer
;
        ldd   glb_camera_x_pos
        subd  glb_camera_x_pos_old
        stb   @b
        addb  scroll_tile_pos_offset24
        cmpb  #24
        blo   >
        subb  #24
        inc   scroll_tile_pos
!       stb   scroll_tile_pos_offset24
        ldb   #0
@b      equ   *-1
        addb  scroll_tile_pos_offset
        cmpb  scroll_tile_width
        blo   >
        subb  scroll_tile_width
        stb   scroll_tile_pos_offset
        ldd   scroll_map_pos           ; next column : one table entry
        addd  #2
        std   scroll_map_pos
        rts
!       stb   scroll_tile_pos_offset
@rts    rts

* ---------------------------------------------------------------------------
* DrawTilesCols
* -------------
* Same prologue as DrawTiles (column count, top-left screen location) ; then
* per visible column : fetch the column list, and for each full cell mount
* the tile's page, add the cell's offset to the column's screen location,
* call the tile. glb_screen_location_1 and U are set the way the compiled
* tiles expect (see DrawTiles).
*
* The cell envelope is kept under the dense engine's (71 cycles against 78,
* and no empty cell is ever visited) : the list is walked with pulu, the
* column top, the buffer delta and the map page are self-modified
* immediates, the list pointer sleeps in a stack slot during the call.
* ---------------------------------------------------------------------------
DrawTilesCols
        lda   glb_camera_move
        bne   @a
        rts
@a
        clra
        sta   glb_Page
        _GetCartPageA
        sta   DrawTilesCols.restoredPage
        lda   scroll_vp_h_tiles
        ldb   scroll_tile_pos_offset
        beq   >
        inca
!       sta   scroll_ccnt
        andb  #%11111110
        negb
        addb  scroll_vp_x_pos
        addb  #80
        lsrb
        lsrb
        bcs   @ram2
        lda   #$C0
        subd  #80/4
        std   <glb_screen_location_2
        suba  #$20
        bra   >
@ram2   lda   #$A0
        subd  #80/4
        std   <glb_screen_location_2
        addd  #$2001
!       std   <glb_screen_location_1
        ldd   <glb_screen_location_2
        subd  <glb_screen_location_1
        std   DrawTilesCols.delta
        leas  -2,s                     ; the list pointer's bed during a call
        ldy   scroll_map_pos           ; Y = the column table entry of the first
        ldd   tile_buffer              ;   visible column
        leay  d,y
        lda   tile_buffer_page
        sta   $E7E6
        sta   DrawTilesCols.mapPage
        lda   scroll_vp_y_pos
        ldb   #40
        mul
        addd  <glb_screen_location_1   ; D = screen location of the column top
DrawTilesCols.column
        std   DrawTilesCols.top
        ldu   ,y++                     ; U = the column's list
        sty   DrawTilesCols.entry
DrawTilesCols.cell
        pulu  b,y                      ; B = the tile's page, Y = its routine
        tstb                           ; 0 = end of column (pulu leaves CC)
        beq   DrawTilesCols.next
        stb   DrawTilesCols.cellPg     ; stash the page NOW : the offset and the
                                       ; page both live in the MAP page, and the
                                       ; pulu below clobbers B — so save it, and
                                       ; read the offset, before paging the map
                                       ; out. tilescroll hid this by keeping its
                                       ; map and tiles in one page.
        pulu  d                        ; the cell's video offset (still map page)
        addd  #0                       ; + the column top
DrawTilesCols.top     equ   *-2
        std   <glb_screen_location_1
        addd  #0                       ; + the buffer delta
DrawTilesCols.delta   equ   *-2
        stu   ,s
        tfr   d,u
        lda   #0                       ; mount the tile's page (self-modified)
DrawTilesCols.cellPg  equ   *-1
        sta   $E7E6
        jsr   ,y
        ldu   ,s
        lda   #0
DrawTilesCols.mapPage equ   *-1
        sta   $E7E6
        bra   DrawTilesCols.cell
DrawTilesCols.next
        lda   DrawTilesCols.mapPage    ; the terminator mounted page 0
        sta   $E7E6
        dec   scroll_ccnt
        beq   @rts
        ldy   DrawTilesCols.entry
        ldd   DrawTilesCols.top
        addb  scroll_mc_step           ; the dense engine's column pixel step
        bcc   DrawTilesCols.column
        inca
        bra   DrawTilesCols.column
@rts    leas  2,s
        lda   #0
DrawTilesCols.restoredPage equ *-1
        _SetCartPageA
        rts
DrawTilesCols.entry   fdb   0
