package com.widedot.m6809.gamebuilder.plugin.direntry;

import java.util.ArrayList;
import com.widedot.m6809.gamebuilder.Handlers;
import com.widedot.m6809.gamebuilder.spi.BuildContext;
import java.util.Arrays;
import java.util.List;

import org.apache.commons.configuration2.tree.ImmutableNode;

import com.widedot.m6809.gamebuilder.plugin.direntry.format.LinkData;
import com.widedot.m6809.gamebuilder.spi.ObjectPluginInterface;
import com.widedot.m6809.gamebuilder.spi.DefaultPluginInterface;
import com.widedot.m6809.gamebuilder.spi.ObjectDataInterface;
import com.widedot.m6809.gamebuilder.spi.configuration.Attribute;
import com.widedot.m6809.gamebuilder.spi.configuration.Defaults;
import com.widedot.m6809.gamebuilder.spi.configuration.Defines;
import com.widedot.m6809.gamebuilder.spi.media.DirEntry;
import com.widedot.m6809.gamebuilder.spi.media.MediaDataInterface;
import com.widedot.m6809.util.zx0.Compressor;
import com.widedot.m6809.util.zx0.Main;
import com.widedot.m6809.util.zx0.Optimizer;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class DirEntryPlugin {

	/** a directory entry stores the file size minus one on 14 bits */
	public static final int MAX_FILE_SIZE = 0x4000;

	/** size of one directory entry block ; a file id is an index of those */
	public static final int BLOCK_SIZE = 8;

	/**
	 * Number of blocks an entry occupies, hence how many file ids it consumes.
	 * DirectoryPlugin reserves ids from the configuration before the entries
	 * exist, and this plugin emits them : both must agree exactly or every
	 * file id after the divergence points at the wrong entry at runtime.
	 *
	 * @param codec       the direntry codec attribute, null when uncompressed
	 * @param linkSection the loadtimelink attribute, null when not linked
	 */
	public static int blockCount(String codec, String linkSection) {
		return 1 + (codec != null ? 1 : 0) + (linkSection != null ? 1 : 0);
	}

	/** the loader copies back exactly 6 uncompressed tail bytes (dir.entry.cdataz) */
	public static final int ZX0_DELTA = 6;

	/**
	 * zx0 optimizer threads. Entries are at most 16 KB, well below the point
	 * where the fan out pays for its synchronisation.
	 */
	private static final int ZX0_THREADS = 1;

	
//	loader direntry for a file (8, 16 or 24 bytes):
//  -----------------------------------------------------------------------------------------------
//	[0] [0]                    - [compression 0:none, 1:packed] [load time linker 0:no, 1:yes]
//	[00 0000] [0000 0000]      - [uncompressed file size -1]
//	[0000 000] [0] [0000 0000] - [track 0-128] [face 0-1] [sector 0-255]
//	[0000 0000] [0000 0000]    - [bytes in first sector] [start offset in first sector (0: no sector)] ($ff00 : empty file)
//	[0000 0000]                - [nb sectors]
//	[0000 0000]                - [bytes in last sector (0: no sector)]
//
//	Option (8 bytes) - compression
//	[0000 0000 0000 0000] - [offset to compressed data]
//	[0000 0000] [0000 0000] [0000 0000] [0000 0000] [0000 0000] [0000 0000] - [6x delta bytes]
//	
//  start >>           |------------------| compressed data
//  |---------------------------------|     decompressed data
//  <------------------>              <--->
//        offset                      delta	
//
//	Option (8 bytes) - load time linker data
//	[0000 0000] [0000 0000]    - [byte size of linker data]
//	[0000 000] [0] [0000 0000] - [track 0-128] [face 0-1] [sector 0-255]
//	[0000 0000] [0000 0000]    - [bytes in first sector] [start offset in first sector (0: no sector)]
//	[0000 0000]                - [nb sectors]
//	[0000 0000]                - [bytes in last sector (0: no sector)]
//
//	ids to direntries are generated by blocks of 8 bytes :
//	ex :
//	file.a equ 0 ; no compression, no load time link => 8  bytes = 1 blocks
//	file.b equ 1 ;    compression, no load time link => 16 bytes = 2 blocks
//	file.c equ 3 ;    compression,    load time link => 24 bytes = 3 blocks
//	file.d equ 6
//	...
	
	public static final String ZX0 = "zx0";
	
	public static void run(ImmutableNode node, BuildContext ctx, MediaDataInterface media) throws Exception {
    	
		log.debug("Processing direntry ...");
		
		String name = Attribute.getString(node, ctx, "name");
		// exports registered while this direntry builds belong to it : the
		// direntry is the unit the loader loads and evicts, so it is the
		// granularity of the export uniqueness rule
		ctx.linkSymbols.beginUnit(name);
		// the consumer whose references the static resolutions below serve —
		// generators (a tilemap asking pageOf) and the bake both run inside
		// this direntry, and a multi-provider symbol is disambiguated by who
		// is asking
		ctx.staticLink.setCurrentConsumer(name);
		String section = Attribute.getString(node, ctx, "section");
		String codec = Attribute.getStringOpt(node, ctx, "codec");
		String linkSection = Attribute.getStringOpt(node, ctx, "loadtimelink");
		boolean loadtimelink = (linkSection!=null?true:false);
		// how this direntry's references are resolved — see BakeMode. Declared
		// here, in the configuration that places everything, never in the
		// source : the same unit can be fully linked in one project and fully
		// baked in another.
		com.widedot.m6809.gamebuilder.spi.globals.BakeMode bake =
				com.widedot.m6809.gamebuilder.spi.globals.BakeMode.parse(
						Attribute.getStringOpt(node, ctx, "bake"));
		// the file size is stored on 14 bits in the directory entry, a bigger
		// file cannot be described whatever the configuration asks for
		int maxsize = Attribute.getInteger(node, ctx, "maxsize", MAX_FILE_SIZE);
		
		// binary data
		List<ObjectDataInterface> objects = new ArrayList<ObjectDataInterface>();
		
		// instanciate local definitions
		// nested containers get their own defaults and defines
		BuildContext localCtx = ctx.child();
		
		for (ImmutableNode child : node.getChildren()) {
			String plugin = child.getNodeName();
		
			DefaultPluginInterface defaultHandler = Handlers.getDefault(plugin);
			ObjectPluginInterface objectHandler = Handlers.getObject(plugin);
		    
	        if (defaultHandler == null && objectHandler == null) {
	        	throw new Exception("Element <" + plugin + "> is not valid here");
	        }
		    
	        if (defaultHandler != null) {
			    log.debug("Running handler: {}", plugin);
			    defaultHandler.run(child, localCtx);
			    ctx.publish(localCtx);
	        }
	        
	        if (objectHandler != null) {
			    objects.add(objectHandler.getObject(child, localCtx));
			    ctx.publish(localCtx);
	        }
    	}

		// init direntry
		byte[] direntry = new byte[24];
		
		// resolve references before anything reads the binaries : a baked
		// reference emits no link data at all. The baking needs to know where
		// each member sits inside the entry — an internal reference resolves
		// against the entry's load address plus that offset. Reading the
		// length before baking is safe : patching changes bytes in place,
		// never the length.
		int bakeBase = 0;
		for (ObjectDataInterface obj : objects) {
			obj.bakeStatic(ctx.staticLink, name, bakeBase, bake);
			bakeBase += obj.getBytes().length;
		}
		
		// merge all binaries, collecting the ranges each object needs kept inside
		// one page ; their offsets shift with whatever precedes them in the file.
		// Exports register for static resolution with the same shifted offsets,
		// so a later unit's *.static section can name them.
		int length = 0;
		java.util.Map<String, int[]> pageSpans = new java.util.LinkedHashMap<String, int[]>();
		for (ObjectDataInterface obj : objects) {
			for (java.util.Map.Entry<String, int[]> span : obj.getPageSpans().entrySet()) {
				pageSpans.put(span.getKey(),
						new int[] { length + span.getValue()[0], length + span.getValue()[1] });
			}
			for (java.util.Map.Entry<String, int[]> export : obj.getExportOffsets().entrySet()) {
				boolean absolute = export.getValue()[1] == 1;
				int value = absolute ? export.getValue()[0] : length + export.getValue()[0];
				ctx.staticLink.registerExport(export.getKey(), name, value, absolute);
			}
			length += obj.getBytes().length;
		}
		
	    if (length > maxsize) {
			String m = "data size " + length + " is over maxsize: " + maxsize;
			log.error(m);
			throw new Exception(m);
	    }

	    if (length > MAX_FILE_SIZE) {
			// the size field is 14 bits wide : it wraps. Loading still works for
			// scenes that give an explicit destination, because that ctx.path is
			// driven by the sector counts, but anything reading the size back
			// (loader.file.malloc, adjacent placement in scene types 10 and 11)
			// will see a truncated value. Raising maxsize is how a project says
			// it knows and accepts that.
			log.warn("{}: size {} exceeds the {} bytes a directory entry can describe,"
					+ " the stored size wraps to {}. Only load this file at an explicit"
					+ " destination and never through loader.file.malloc.",
					name, length, MAX_FILE_SIZE, ((length-1) & 0x3fff) + 1);
	    }
		
		byte[] bin = new byte[length];
		
		int o = 0;
		for (ObjectDataInterface obj : objects) {
			byte[] sbin = obj.getBytes();
			for (int i=0; i< sbin.length; i++) {
				bin[o++] = sbin[i];
			}
		}		
		
		// apply codec
		boolean compress = false;
	    int maxdelta = Integer.parseInt(ctx.settings.get("direntry.zx0.delta"));
	    if (maxdelta != ZX0_DELTA) {
			throw new Exception("direntry.zx0.delta must be " + ZX0_DELTA
					+ ", the loader copies back a fixed size tail (dir.entry.cdataz)");
	    }
		if (codec != null) {
			
			if (codec.equals(ZX0)) {
				
				if (length > maxdelta) {
				
					log.debug("Compress data with zx0");
					int[] delta = { 0 };				
					
					// prepare data, shorten by n bytes (maxdelta)
					byte[] sbin = new byte[bin.length-maxdelta];
					System.arraycopy(bin, 0, sbin, 0, sbin.length);
					
					// compress the shortened data
					// 3rd argument is the zx0 search window, not a size cap : it must
					// stay the format constant the 6809 decompressor expects
					byte[] cbin = new Compressor().compress(
							new Optimizer().optimize(sbin, 0, Main.MAX_OFFSET_ZX0, ZX0_THREADS, false),
							bin, 0, false, false, delta);
					log.debug("Original size: {}+{}, Packed size: {}, Delta: {}", bin.length-maxdelta, maxdelta, cbin.length, delta[0]);
					
					// automatic selection of compressed or uncompressed data
					if (delta[0] > maxdelta) {
						log.error("Unable to compress: delta ({}) is higher than max delta.", delta[0]);
						
					} else if (bin.length <= cbin.length+maxdelta) {
						log.error("Unable to compress: compressed data size of {} is bigger or equal to original size.", length);
						
					} else {
										
						// build direntry data (compression bloc)
						int offset = bin.length-cbin.length;
						direntry[8] = (byte) ((offset >>8) & 0xff);
						direntry[9] = (byte) (offset & 0xff);
						
						// copy delta bytes
						System.arraycopy(bin, bin.length-maxdelta, direntry, 10, maxdelta);
						
						bin = cbin;
						compress = true;
					}
				} else {
					log.warn("Unable to compress: data size of {} is lower or equal to max delta bytes", length);
				}
			}
		}
		
		if (codec != null && compress == false) {
			String m = "Build aborted, please remove codec for direntry: " + name;
			log.error(m);
			throw new Exception(m);
		}
				
		// write file to media
	    byte[] dataDiskLocation = media.cwrite(section, bin);
	    
		// process link data first to determine if we actually have link data
		boolean hasLinkData = false;
		LinkData linkdata = null;
		byte[] linkDiskLocation = null;
		
		if (loadtimelink) {
			// aggregate all link data
			linkdata = new LinkData();
			int linkBase = 0;
			for (ObjectDataInterface obj : objects) {
				linkdata.add(obj, linkBase);
				linkBase += obj.getBytes().length;
			}
			linkdata.process();
			
			// A block whose six counters are all zero carries nothing : the
			// bake resolved every reference and the pruning removed every
			// export. Not writing it is what makes a fully baked file cost
			// the loader NOTHING — no link file on disk, no index slot, no
			// pool allocation, no entry every symbol search walks past. The
			// direntry keeps its reserved descriptor size (file ids derive
			// from the attributes before anything is built), only the flag
			// stays down. An export still imported keeps its counter above
			// zero, so this can never drop a block the loader needs.
			if (linkdata.countExportAbs() + linkdata.countExportRel()
					+ linkdata.countIntern() + linkdata.countExtern8()
					+ linkdata.countExtern16() + linkdata.countExternPage() > 0) {
				linkDiskLocation = media.cwrite(linkSection, linkdata.data);
				hasLinkData = true;
			}
		}

		// what this entry costs the loader's memory pool while it stays indexed,
		// for the report the target prints at the end. Observational only.
		int baked = 0;
		for (ObjectDataInterface obj : objects) {
			baked += obj.getBakedCount();
		}
		ctx.linkReport.add(new com.widedot.m6809.gamebuilder.spi.globals.LinkReport.Entry(
				name,
				hasLinkData ? linkdata.data.length : 0,
				linkdata == null ? 0 : linkdata.countIntern(),
				linkdata == null ? 0 : linkdata.countExtern8(),
				linkdata == null ? 0 : linkdata.countExtern16(),
				linkdata == null ? 0 : linkdata.countExternPage(),
				linkdata == null ? 0 : linkdata.countExportAbs(),
				linkdata == null ? 0 : linkdata.countExportRel(),
				baked,
				loadtimelink));
		
		// build direntry data
	    int i = 0;
		if (compress)     direntry[i] = (byte) (direntry[i] | 0b10000000);
		if (hasLinkData)  direntry[i] = (byte) (direntry[i] | 0b01000000);
		int encodedLength = (length-1) & 0x3fff;
		direntry[i] = (byte) (direntry[i] | (encodedLength >> 8)); // uncompressed file size -1 (max 0x4000 bytes) HIGH BYTE
		i++;
		
		direntry[i++] = (byte) (encodedLength & 0xff); // uncompressed file size -1 (max 0x4000 bytes) LOW BYTE
		
		System.arraycopy(dataDiskLocation, 0, direntry, i, 6);
		i += 6;
		
		if (compress) i += 8;
		
		if (hasLinkData) {
			direntry[i++] = (byte)((linkdata.data.length >> 8) & 0xff);
			direntry[i++] = (byte)(linkdata.data.length & 0xff);
			
			System.arraycopy(linkDiskLocation, 0, direntry, i, 6);
			i += 6;
		} else if (loadtimelink) {
			// the descriptor size was reserved from the attribute — keep it,
			// zeroed : with the flag down the loader never reads these bytes
			i += 8;
		}
			
		int expected = blockCount(codec, linkSection) * BLOCK_SIZE;
		if (i != expected) {
			throw new Exception(name + ": emitted a " + i + " byte directory entry while "
					+ expected + " bytes were reserved for it. File ids are indexes into"
					+ " the directory, so every following file would be misread.");
		}

		byte[] sizedDirentry = Arrays.copyOf(direntry, i);
	    media.addDirEntry(new DirEntry(name, sizedDirentry, length, pageSpans));
		
	    String fLength = String.format("%5d", length);
	    log.info("file {} | {} bytes", name, fLength);
		log.debug("End of processing direntry");
	}
	
}
