        INCLUDE "new-engine/system/mo6/map.const.asm"
        INCLUDE "new-engine/global/glb.const.asm"
        INCLUDE "new-engine/6809/macros.asm"
        INCLUDE "new-engine/global/glb.macro.asm"
        INCLUDE "new-engine/system/mo6/ram/ram.macro.asm"
        INCLUDE "new-engine/system/mo6/bootloader/loader.macro.asm"