#!/usr/bin/env python3
"""Generate the tile scroll example's map, as a tile index .bin.

The map is the same file shape leanscroll writes and the <tilemap> element
reads : 16 bit big endian tile indexes, column major. The builder turns each
index into the three byte run-time entry — page byte and address word of the
compiled tile routine — baked in a map.static section, exactly what v1's
generator did after placement.

Index 0 is the "draw nothing" convention, so the sheet's tile 0 is a poison
tile the map never references : real tiles are 1..4.

The pattern is a ruler, not a landscape. Column parity alternates two flat
tiles so a column read from the wrong map is obvious, every fourth column is
a framed tile so counting is possible, and a diagonal runs along the top row
so a broken tile boundary shows as a broken line.
"""
import struct

COLS, ROWS = 24, 8

def tile_at(col, row):
    if row == 0:
        return 3                          # the diagonal ribbon
    if col % 4 == 0:
        return 4                          # a counting mark every 4 columns
    return 1 if (col % 2 == 0) else 2

with open('src/assets/maps/map.bin', 'wb') as f:
    for col in range(COLS):
        for row in range(ROWS):
            f.write(struct.pack('>H', tile_at(col, row)))

open('src/assets/maps/map.const.asm', 'w').write(f"""* ===========================================================================
* Test map geometry — generated by tools/gen_testmap.py, do not edit
* ===========================================================================
map.COLS  equ {COLS}
map.ROWS  equ {ROWS}
""")
print(f"map.bin : {COLS}x{ROWS} indexes 16 bits BE, colonne-major")
