#!/usr/bin/env python3
"""Generate the tile scroll example's map.

The scroll reads a column-major table of three byte entries — one page byte
and one address word per tile, pointing straight at a compiled tile routine,
with no tile index in between. It reads two of them: the even map holds the
unshifted tile variants, the odd map the one pixel pre-shifted ones, which is
how a 1px scroll costs nothing at run time.

The pattern is a ruler, not a landscape. Column parity alternates two flat
tiles so a column read from the wrong map is obvious, every fourth column is
a framed tile so counting is possible, and a diagonal runs along the top row
so a broken tile boundary shows as a broken line.
"""
COLS, ROWS = 24, 8
TILES = ['tile0', 'tile1', 'tile2', 'tile3']

def tile_at(col, row):
    if row == 0:
        return 'tile2'                    # the diagonal ribbon
    if col % 4 == 0:
        return 'tile3'                    # a counting mark every 4 columns
    return 'tile0' if (col % 2 == 0) else 'tile1'

def table(name, suffix):
    out = [f"{name}"]
    for col in range(COLS):
        out.append(f"        ; column {col}")
        for row in range(ROWS):
            t = tile_at(col, row)
            out.append(f"        fcb   assets.tiles$PAGE+$60")
            out.append(f"        fdb   adr_{t}_{suffix}")
    return "\n".join(out)

hdr = f"""* ===========================================================================
* Test map — generated by tools/gen_testmap.py, do not edit
* ===========================================================================
* {COLS} columns of {ROWS} tiles, column major, three bytes per tile :
*   page    (byte) page holding the compiled tile routine
*   address (word) its entry point
*
* Two maps : the even one uses the unshifted tile variants, the odd one the
* pre-shifted ones. The scroll picks between them on the parity of the camera.

map.COLS  equ {COLS}
map.ROWS  equ {ROWS}
"""
open('src/assets/maps/testmap.asm','w').write(
    hdr + "\n" + table('map.even', 'ND0') + "\n\n" + table('map.odd', 'ND1') + "\n")
print(f"carte {COLS}x{ROWS} ecrite, {COLS*ROWS*3} octets par plan")
