package com.widedot.m6809.gamebuilder.plugin.tilemap;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.configuration2.tree.ImmutableNode;

import com.widedot.m6809.gamebuilder.spi.BuildContext;
import com.widedot.m6809.gamebuilder.spi.configuration.Attribute;

import lombok.extern.slf4j.Slf4j;

/**
 * Handler for the &lt;tilereset&gt; element : from a list of map RECTANGLES,
 * emit what puts those cells back the way the level shipped them.
 *
 * <p><b>Why it exists.</b> {@code tilemap.patch} rewrites cells of the scroll
 * map in place, and the map in RAM is the only copy — the original is gone the
 * moment an animation runs. A checkpoint return does NOT reload the stage from
 * disk : it repaints from those same tables. Without a snapshot, the decor
 * stays frozen in whatever frame was last written.</p>
 *
 * <p><b>What it costs : pointers, not tiles.</b> A restore cell names the
 * LEVEL's tile — {@code adr_<levelTiles>_<id>_<variant>} — so nothing is
 * compiled twice. Measured on r-type's stage 2 : the five patchable rectangles
 * cover 68 cells over 46 distinct tiles, all of them already in the level's
 * tileset, for 204 bytes of pointers. Drawing those rest states as art instead
 * would have recompiled the 46 tiles, some 8.7 KB.</p>
 *
 * <p><b>The shape of the output is the trick.</b> Each rectangle becomes a
 * descriptor of ONE frame, exactly like {@link TilepatchPlugin}'s, holding the
 * map's own cells ; and the table is a run of ready-made ring entries. Putting
 * things back is then a block copy into the request ring — the drain applies
 * them without knowing they are a restore, and the runtime needs no
 * restore-specific path at all.</p>
 *
 * <p>Index 0 keeps its meaning through the round trip : a cell the map leaves
 * empty is restored empty, which is what has to happen where an animation
 * painted over sky.</p>
 */
@Slf4j
public class TileresetPlugin {

	public static File getFile(ImmutableNode node, BuildContext ctx) throws Exception {

		String map = ctx.path + File.separator + Attribute.getString(node, ctx, "map");
		String label = Attribute.getString(node, ctx, "label");
		String tiles = Attribute.getString(node, ctx, "tiles");
		String variant = Attribute.getString(node, ctx, "variant");
		String gensource = ctx.path + File.separator + Attribute.getString(node, ctx, "gensource");
		String genhead = Attribute.getStringOpt(node, ctx, "genhead");
		String headsection = Attribute.getString(node, ctx, "headsection", "code");
		String section = Attribute.getString(node, ctx, "section", "map");
		int bitdepth = Attribute.getInteger(node, ctx, "bitdepth", 16);
		int rows = Attribute.getInteger(node, ctx, "maprows");

		if (bitdepth != 8 && bitdepth != 16) {
			throw new Exception("tilereset " + label + " : bitdepth must be 8 or 16");
		}

		byte[] data = Files.readAllBytes(Paths.get(map));
		int step = bitdepth / 8;
		int entries = data.length / step;
		int cols = entries / rows;
		if (cols * rows != entries) {
			throw new Exception("tilereset " + label + " : " + map + " holds " + entries
					+ " indexes, not a whole number of columns of " + rows);
		}

		List<int[]> rects = new ArrayList<int[]>();
		for (ImmutableNode child : node.getChildren()) {
			if (!"rect".equals(child.getNodeName())) {
				continue;
			}
			int c = Attribute.getInteger(child, ctx, "col");
			int r = Attribute.getInteger(child, ctx, "row");
			int w = Attribute.getInteger(child, ctx, "cols");
			int h = Attribute.getInteger(child, ctx, "rows");
			if (w < 1 || h < 1 || c < 0 || r < 0 || c + w > cols || r + h > rows) {
				throw new Exception("tilereset " + label + " : rect (" + c + "," + r + ") "
						+ w + "x" + h + " falls outside the " + cols + "x" + rows + " map");
			}
			rects.add(new int[] { c, r, w, h });
		}
		if (rects.isEmpty()) {
			throw new Exception("tilereset " + label + " : no <rect>, nothing to restore");
		}
		if (rects.size() > 255) {
			throw new Exception("tilereset " + label + " : " + rects.size()
					+ " rectangles, the table counts them in one byte");
		}

		com.widedot.m6809.gamebuilder.spi.globals.Machines.Machine machine =
				ctx.machines.required("<tilereset>");

		// Which tiles the restore names — the LEVEL's, gathered first so the
		// generated file can declare its own externals.
		java.util.TreeSet<Integer> used = new java.util.TreeSet<Integer>();
		for (int[] q : rects) {
			for (int c = q[0]; c < q[0] + q[2]; c++) {
				for (int r = q[1]; r < q[1] + q[3]; r++) {
					int i = c * rows + r;
					int id = step == 1 ? data[i] & 0xFF
							: ((data[i * 2] & 0xFF) << 8) | (data[i * 2 + 1] & 0xFF);
					if (id != 0) {
						used.add(id);
					}
				}
			}
		}

		StringBuilder s = new StringBuilder();
		String nl = System.lineSeparator();
		s.append("* Generated by tilereset from ").append(map).append(nl);
		s.append("* ").append(rects.size()).append(" rectangle(s), ")
				.append(used.size()).append(" distinct tiles of ").append(tiles).append(nl);
		s.append("        INCLUDE \"").append(machine.pageInclude).append('"').append(nl);
		for (int id : used) {
			String t = "adr_" + tiles + "_" + id + "_" + variant;
			s.append(t).append(" EXTERNAL").append(nl);
			s.append(t).append("$PAGE EXTERNAL").append(nl);
		}
		// LA TETE SE SEPARE DU CORPS quand genhead est donne. Elle seule est lue
		// par tilemap.restore, et la lire depuis une page montee etait la raison
		// d'etre du montage dans cette routine : posee dans l'unite residente du
		// stage, la restauration redevient une copie d'octets. Le corps —
		// descripteurs, tables et blocs — reste avec la carte, ou tilemap.flush
		// va le chercher sous la page du plan pair, comme pour toute animation.
		StringBuilder h = genhead == null ? s : new StringBuilder();
		if (genhead != null) {
			h.append("* Generated by tilereset from ").append(map).append(nl);
			h.append("* La tete de table : ").append(rects.size())
					.append(" entree(s) d'anneau, a assembler dans l'unite RESIDENTE")
					.append(nl);
			h.append("* du stage — celle qui arme tilemap.resetTable.").append(nl);
			for (int k = 0; k < rects.size(); k++) {
				h.append(label).append(".d").append(k).append(" EXTERNAL").append(nl);
				s.append(label).append(".d").append(k).append(" EXPORT").append(nl);
			}
			h.append(" SECTION ").append(headsection).append(nl);
		} else {
			s.append(label).append(" EXPORT").append(nl);
			s.append(" SECTION ").append(section).append(nl);
		}

		// The table : a count, then one ready-made ring entry per rectangle.
		h.append(label).append(nl);
		h.append("        fcb   ").append(rects.size()).append("        ; rectangles").append(nl);
		for (int k = 0; k < rects.size(); k++) {
			h.append("        fdb   ").append(label).append(".d").append(k).append(nl);
			h.append("        fcb   0        ; image unique").append(nl);
		}
		if (genhead != null) {
			h.append(" ENDSECTION").append(nl);
			s.append(" SECTION ").append(section).append(nl);
		}

		int cells = 0;
		int empty = 0;
		for (int k = 0; k < rects.size(); k++) {
			int[] q = rects.get(k);
			s.append(label).append(".d").append(k).append(nl);
			s.append("        fcb   ").append(q[2]).append(',').append(q[3])
					.append(",1,").append(q[0]).append(',').append(q[1])
					.append(",1        ; cols, rows, frames, col, row, hold").append(nl);
			// tableEven pointe une TABLE de pointeurs d'images, pas le bloc :
			// une seule entree ici, l'image de repos.
			s.append("        fdb   ").append(label).append(".t").append(k).append(nl);
			s.append("        fdb   0        ; pas de plan impair : la restauration").append(nl);
			s.append("                       ; suit le plan que l'animation a patche").append(nl);
			s.append(label).append(".t").append(k).append(nl);
			s.append("        fdb   ").append(label).append(".b").append(k).append(nl);
		}
		for (int k = 0; k < rects.size(); k++) {
			int[] q = rects.get(k);
			s.append(label).append(".b").append(k).append(nl);
			// column major, like the map and like <tilepatch>'s blocks
			for (int c = q[0]; c < q[0] + q[2]; c++) {
				for (int r = q[1]; r < q[1] + q[3]; r++) {
					int i = c * rows + r;
					int id = step == 1 ? data[i] & 0xFF
							: ((data[i * 2] & 0xFF) << 8) | (data[i * 2 + 1] & 0xFF);
					cells++;
					if (id == 0) {
						s.append("        fcb   0").append(nl);
						s.append("        fdb   0").append(nl);
						empty++;
						continue;
					}
					String sym = "adr_" + tiles + "_" + id + "_" + variant;
					s.append("        fcb   ").append(machine.pageExpr).append(sym)
							.append("$PAGE").append(nl);
					s.append("        fdb   ").append(sym).append(nl);
				}
			}
		}
		s.append(" ENDSECTION").append(nl);

		if (genhead != null) {
			Path hp = Paths.get(ctx.path + File.separator + genhead);
			if (hp.getParent() != null) {
				Files.createDirectories(hp.getParent());
			}
			Files.writeString(hp, h.toString());
		}

		Path path = Paths.get(gensource);
		if (path.getParent() != null) {
			Files.createDirectories(path.getParent());
		}
		Files.writeString(path, s.toString());
		log.info("tilereset {} : {} rectangle(s), {} cells ({} empty) over {} tiles already in {}, "
				+ "{} bytes of pointers", label, rects.size(), cells, empty, used.size(), tiles,
				cells * 3);
		return path.toFile();
	}
}
