package com.widedot.m6809.gamebuilder.plugin.tilemap;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.apache.commons.configuration2.tree.ImmutableNode;

import com.widedot.m6809.gamebuilder.spi.BuildContext;
import com.widedot.m6809.gamebuilder.spi.configuration.Attribute;

import lombok.extern.slf4j.Slf4j;

/**
 * Handler for the &lt;tilemap&gt; element : turns a tile index map into the
 * page/address table the scroll engine walks, as a generated source of the
 * surrounding &lt;lwasm&gt; unit.
 *
 * The input is what leanscroll writes : tile indexes, 16 bits big endian (or
 * 8 bits), already transposed to column major. Each index becomes three bytes,
 * the run-time entry of one tile :
 *
 *     fcb   &lt;file&gt;$PAGE+$60          page holding the compiled tile
 *     fdb   adr_&lt;tiles&gt;_&lt;id&gt;_&lt;variant&gt;   its entry point
 *
 * Index 0 is the v1 convention for "nothing to draw" and becomes three zero
 * bytes — the scroll skips the entry (BuildDisk generated the same shape from
 * the same .bin files).
 *
 * The table's references are baked by the builder : the file holding it
 * reference against the declared placement of the tiles' file, so the
 * hundreds of entries cost no load-time link data and no run-time symbol
 * search. This is also how v1 paid for its maps — values resolved at build
 * time, placed after the tiles were.
 */
@Slf4j
public class TilemapPlugin {

	public static File getFile(ImmutableNode node, BuildContext ctx) throws Exception {

		String map = ctx.path + File.separator + Attribute.getString(node, ctx, "map");
		String label = Attribute.getString(node, ctx, "label");
		String tiles = Attribute.getString(node, ctx, "tiles");
		String variant = Attribute.getString(node, ctx, "variant");
		String gensource = ctx.path + File.separator + Attribute.getString(node, ctx, "gensource");
		String section = Attribute.getString(node, ctx, "section", "map");
		int bitdepth = Attribute.getInteger(node, ctx, "bitdepth", 16);

		if (bitdepth != 8 && bitdepth != 16) {
			throw new Exception("tilemap " + label + " : bitdepth must be 8 or 16");
		}
		// the whole point of the element is the baked table : the file
		// holding it declares bake="all", the section name is an identity

		byte[] data = Files.readAllBytes(Paths.get(map));
		int step = bitdepth / 8;
		if (data.length % step != 0) {
			throw new Exception("tilemap " + label + " : " + map + " is " + data.length
					+ " bytes, not a whole number of " + bitdepth + " bit indexes");
		}
		int entries = data.length / step;

		int[] ids = new int[entries];
		java.util.TreeSet<Integer> used = new java.util.TreeSet<Integer>();
		for (int i = 0; i < entries; i++) {
			ids[i] = step == 1 ? data[i] & 0xFF
					: ((data[i * 2] & 0xFF) << 8) | (data[i * 2 + 1] & 0xFF);
			if (ids[i] != 0) {
				used.add(ids[i]);
			}
		}

		StringBuilder source = new StringBuilder();
		source.append("* Generated by tilemap from ").append(map).append(System.lineSeparator());
		source.append("* ").append(entries).append(" entries of 3 bytes, column major,")
				.append(" tiles ").append(tiles).append(" variant ").append(variant)
				.append(System.lineSeparator());
		// the generated file declares its own externals — a real tileset has
		// hundreds of tiles, nobody hand-writes those. lwasm accepts the same
		// symbol declared EXTERNAL by several files of a unit
		for (int id : used) {
			source.append("adr_").append(tiles).append('_').append(id).append('_')
					.append(variant).append(" EXTERNAL").append(System.lineSeparator());
		}
		// The table is exported : a map big enough to need its own page lives
		// in a file of its own, and the game mode then reaches it by name.
		// When it stays in the unit that uses it, the export costs nothing —
		// nothing imports it, so pruning leaves it out of the link data.
		source.append(label).append(" EXPORT").append(System.lineSeparator());
		source.append(" SECTION ").append(section).append(System.lineSeparator());
		source.append(label).append(System.lineSeparator());
		// the page byte's prefix is a MACHINE fact, declared in the machine
		// definitions — never a constant of the builder (§26)
		String pageExpr = ctx.machines.required("<tilemap>").pageExpr;
		int empty = 0;
		for (int i = 0; i < entries; i++) {
			if (ids[i] == 0) {
				// v1 convention : index 0 draws nothing
				source.append("        fcb   0").append(System.lineSeparator());
				source.append("        fdb   0").append(System.lineSeparator());
				empty++;
				continue;
			}
			// The page is asked per symbol, not once for the whole table : a
			// tileset too big for one page is spread over several, and then
			// two entries of the same map legitimately carry different pages.
			// It also costs nothing at load time — a literal, not a reference.
			String symbol = "adr_" + tiles + "_" + ids[i] + "_" + variant;
			source.append("        fcb   ").append(pageExpr)
					.append(ctx.staticLink.pageOf(symbol)).append(System.lineSeparator());
			source.append("        fdb   ").append(symbol).append(System.lineSeparator());
		}
		source.append(" ENDSECTION").append(System.lineSeparator());

		Path path = Paths.get(gensource);
		if (path.getParent() != null) {
			Files.createDirectories(path.getParent());
		}
		Files.writeString(path, source.toString());
		log.info("tilemap {} : {} entries ({} empty), {} bytes at run time",
				label, entries, empty, entries * 3);
		return path.toFile();
	}
}
