; ===========================================================================
; playfield.clearBlast — l'effacement du champ de jeu, a fenetre PILOTEE.
; ===========================================================================
; Le remplissage est un stack-blast PSHS A,B,DP,X,Y,U (9 octets/14 cycles,
; 1,556 cy/octet), ENTIEREMENT deroule, pleine largeur, qui descend du bas
; de la fenetre vers le haut. Deux parametres le pilotent, poses par
; playfield.clearWindow (SMC, la page est de la RAM-sur-cartouche) :
;
;   - l'operande du LDS   : OU commence la descente (la borne BASSE) ;
;   - l'operande du JMP   : ou l'on SAUTE dans le deroule — chaque poussee
;     zappee retire 9 octets en tete de descente, c'est la borne HAUTE.
;
; La fenetre maximale est TOUT le champ de jeu, lignes 11 a 190 (au-dessus
; et en-dessous, c'est le masque) : 7 200 octets par plan, 800 poussees —
; la division tombe juste. Le blast ne presume RIEN du decor : ce que la
; tilemap repeint a coup sur (la rangee du bas, un plafond continu...) est
; l'affaire de la TIMELINE par stage, generee depuis la carte par
; gen_clear_timeline.py — elle ne stocke que les changements, precalcules :
; [camera(2), operande LDS plan couleur(2), offset de saut(2)]. Le plan
; forme se deduit (+$2000, meme offset). Le nombre de poussees d'une
; fenetre est arrondi AU-DESSUS : le depassement (<= 8 octets) sort par la
; borne haute, dans des lignes zappees ou masquees — jamais sous $A000.
;
; Pieges payes et graves ici (cf. l'historique du fichier) :
;   - AUCUN bsr/rts quand S est le pointeur d'ecriture (l'adresse de retour
;     se depile 7 000 octets plus bas, dans les zeros frais) ;
;   - CC est INPOUSSABLE sous IRQ ouvertes (l'IRQ materielle force E=1 dans
;     le CC qu'elle empile et le RTI restaure CE CC-la) — d'ou 9 octets ;
;   - S est legal comme pointeur : l'IRQ v2 bascule S en premiere
;     instruction, seul le push materiel touche la zone pas encore ecrite ;
;   - DP passe a zero (le moniteur pose le sien en tete d'IRQ).
;
; Etat assemble (et defaut des stages sans timeline) : fenetre pleine,
; 22 455 cycles. Chaque rangee de tuiles zappee rend ~747 cycles de PSHS.
; ===========================================================================

; DEUX ENTREES FIXES, UN SEUL DEROULE (06/09/2026, decision auteur) : le
; deroule couvre les 200 lignes (889 poussees, 8 001 octets) ; l'entree
; plein ecran part un octet plus haut que la fin du tampon ($BF41) pour que
; l'octet en trop tombe sur $BF40, apres le tampon et dans la fenetre video,
; jamais dans la page directe ; l'entree champ de jeu (lignes 11-190, le HUD
; du stage intact) entre 89 poussees plus loin. La fenetre dynamique (pose
; par timeline, conversion de lignes) est retiree : les deux usages sont
; fixes, et ses 4 operandes ne sont plus poses que par ces deux entrees.
NPUSH    equ 889                       ; 200 lignes x 40 / 9, arrondi au-dessus
NPUSH_FIELD equ 800                    ; 180 lignes : le champ 11-190

playfield.clearBlast     EXPORT      ; le champ de jeu, lignes 11-190
playfield.clearBlastFull EXPORT      ; tout l'ecran, lignes 0-199

 SECTION code

 OPT C,CT

playfield.clearBlast
        ldy   #$A000+191*40            ; borne basse : la ligne 190
        ldu   #(NPUSH-NPUSH_FIELD)*2   ; 800 poussees : l'entree saute les 89 premieres
        bra   clr.run
playfield.clearBlastFull
        ldy   #$A000+200*40+1          ; un octet plus haut que la fin du tampon
        ldu   #0                       ; tout le deroule
clr.run
        sty   >clr.ldsA+2              ; les quatre operandes du deroule
        tfr   y,d
        addd  #$2000
        std   >clr.ldsB+2
        tfr   u,d
        addd  #clr.blockA
        std   >clr.jmpA+1
        tfr   u,d
        addd  #clr.blockB
        std   >clr.jmpB+1
        sts   >glb_register_s          ; meme convention que les sprites bdraw
        clra
        clrb
        tfr   a,dp                     ; DP=0 : il fait partie des octets pousses
        ldx   #0
        ldy   #0
        ldu   #0

clr.ldsA
        lds   #$A000+191*40            ; plan couleur — operande PILOTE (borne basse)
clr.jmpA
        jmp   clr.blockA               ; operande PILOTE (borne haute)
clr.blockA
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
clr.ldsB
        lds   #$C000+191*40            ; plan forme — pose par clearWindow (+$2000)
clr.jmpB
        jmp   clr.blockB
clr.blockB
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        pshs  a,b,dp,x,y,u
        lda   #dp/256                  ; DP moteur ($9F) — la page directe du jeu
        tfr   a,dp
        lds   >glb_register_s
        rts

 ENDSECTION
