; GENERE par tools/gen_warship_slices.py — les tranches, resolues au chargement.
set_core_closed_0  EXTERNAL
set_core_closed_1  EXTERNAL
set_core_closed_2  EXTERNAL
set_core_closed_3  EXTERNAL
set_core_closed_4  EXTERNAL
set_core_closed_5  EXTERNAL
set_core_closed_6  EXTERNAL
set_core_closed_7  EXTERNAL
set_core_closed_8  EXTERNAL
set_core_closed_9  EXTERNAL
set_core_closed_10  EXTERNAL
set_core_closed_11  EXTERNAL
set_core_closed_12  EXTERNAL
set_core_closed_13  EXTERNAL
set_core_closed_14  EXTERNAL
set_core_closed_15  EXTERNAL
set_core_closed_16  EXTERNAL
set_core_closed_17  EXTERNAL
set_core_closed_18  EXTERNAL
set_core_closed_19  EXTERNAL
set_core_closed_20  EXTERNAL
set_core_closed_21  EXTERNAL
set_core_closed_22  EXTERNAL
set_core_closed_23  EXTERNAL
set_core_closed_24  EXTERNAL
set_core_closed_25  EXTERNAL
set_core_closed_26  EXTERNAL
set_core_closed_27  EXTERNAL
set_core_opening_0  EXTERNAL
set_core_opening_1  EXTERNAL
set_core_opening_2  EXTERNAL
set_core_opening_3  EXTERNAL
set_core_opening_4  EXTERNAL
set_core_opening_5  EXTERNAL
set_core_open_0  EXTERNAL
set_core_open_1  EXTERNAL
set_core_open_flash_0  EXTERNAL
set_core_open_flash_1  EXTERNAL
