; GENERE par tools/gen_warship_slices.py — les tranches, resolues au chargement.
set_core_anim_0  EXTERNAL
set_core_anim_1  EXTERNAL
set_core_anim_2  EXTERNAL
set_core_anim_3  EXTERNAL
set_core_anim_4  EXTERNAL
set_core_anim_5  EXTERNAL
set_core_anim_6  EXTERNAL
set_core_anim_7  EXTERNAL
set_core_anim_8  EXTERNAL
set_core_anim_9  EXTERNAL
set_core_anim_10  EXTERNAL
set_core_anim_11  EXTERNAL
set_core_anim_12  EXTERNAL
set_core_anim_13  EXTERNAL
set_core_anim_14  EXTERNAL
set_core_anim_15  EXTERNAL
set_core_opening_0  EXTERNAL
set_core_opening_1  EXTERNAL
set_core_opening_2  EXTERNAL
set_core_opening_3  EXTERNAL
set_core_opening_4  EXTERNAL
set_core_opening_5  EXTERNAL
set_core_opening_6  EXTERNAL
set_core_opening_7  EXTERNAL
set_core_opening_8  EXTERNAL
set_core_opening_9  EXTERNAL
set_core_opening_10  EXTERNAL
set_core_opening_11  EXTERNAL
set_core_opening_12  EXTERNAL
set_core_opening_13  EXTERNAL
set_core_opening_14  EXTERNAL
set_core_opening_15  EXTERNAL
set_core_opening_16  EXTERNAL
set_core_opening_17  EXTERNAL
set_core_opening_18  EXTERNAL
set_core_opening_19  EXTERNAL
set_core_opening_20  EXTERNAL
set_core_opening_21  EXTERNAL
set_core_opening_22  EXTERNAL
set_core_opening_23  EXTERNAL
set_core_opening_24  EXTERNAL
set_core_opening_25  EXTERNAL
set_core_opening_26  EXTERNAL
set_core_opening_27  EXTERNAL
set_core_opening_28  EXTERNAL
set_core_opening_29  EXTERNAL
set_core_opening_30  EXTERNAL
set_core_opening_31  EXTERNAL
set_core_open_0  EXTERNAL
set_core_open_1  EXTERNAL
set_core_open_2  EXTERNAL
set_core_open_3  EXTERNAL
set_core_cover_0  EXTERNAL
set_core_cover_1  EXTERNAL
set_core_cover_2  EXTERNAL
set_core_cover_3  EXTERNAL
set_core_cover_4  EXTERNAL
set_core_cover_5  EXTERNAL
set_core_cover_6  EXTERNAL
set_core_cover_7  EXTERNAL
