package com.widedot.m6809.gamebuilder.config;

import java.io.File;
import java.io.FileWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.commons.configuration2.tree.ImmutableNode;

import com.widedot.m6809.gamebuilder.spi.BuildContext;
import com.widedot.m6809.gamebuilder.spi.configuration.Attribute;
import com.widedot.m6809.gamebuilder.spi.globals.Compositions;
import com.widedot.m6809.gamebuilder.spi.globals.DirReservations;
import com.widedot.m6809.util.FileUtil;

/**
 * Reads the {@code <composition>} declarations, and turns them into the table
 * the game hands to the loader.
 *
 * <p>Read TWICE, like the layout's regions : once by the placement scan, which
 * needs them before anything assembles, and once by the layout plugin, which
 * declares them for the end-of-target checks. Only the second writes into the
 * context — a declaration read twice must not become two declarations.</p>
 *
 * <p><b>The table is generated source, not a file on the media.</b> A scene
 * table is a directory entry because the loader discovers it at run time ; a
 * composition is known at build time and is read by the loader itself, so
 * putting it on the disk would cost an entry, a read and a directory slot for
 * nothing — and directory slots are exactly what a full game has none of (the
 * r-type library directory refuses a fifty-first entry). It is emitted as
 * equates the game includes, like the layout's, and the game passes its
 * address.</p>
 *
 * <p>Ids are written as literals rather than as references to the directories'
 * generated equates : a composition spans directories, so a symbolic table
 * would have to include several {@code entries.asm} files and would inherit
 * their order. The scene each number stands for is written beside it.</p>
 */
public final class CompositionScan {

	private CompositionScan() {
	}

	/**
	 * @return the compositions declared by this layout, in declaration order,
	 *         without touching the context
	 */
	public static List<Compositions.Composition> parse(ImmutableNode layout, BuildContext ctx)
			throws Exception {
		List<Compositions.Composition> found = new ArrayList<Compositions.Composition>();
		for (ImmutableNode child : layout.getChildren()) {
			if (!"composition".equals(child.getNodeName())) {
				continue;
			}
			List<String> scenes = new ArrayList<String>();
			for (ImmutableNode member : child.getChildren()) {
				if (!"scene".equals(member.getNodeName())) {
					throw new Exception(ctx.sources.locate(member) + ": <composition> only"
							+ " contains <scene> elements, found <" + member.getNodeName() + ">");
				}
				String scene = Attribute.getString(member, ctx, "name");
				if (scenes.contains(scene)) {
					throw new Exception(ctx.sources.locate(member) + ": composition '"
							+ Attribute.getString(child, ctx, "name") + "' names the scene '"
							+ scene + "' twice");
				}
				scenes.add(scene);
			}
			found.add(new Compositions.Composition(Attribute.getString(child, ctx, "name"),
					scenes, ctx.sources.locate(child)));
		}
		return found;
	}

	/**
	 * Writes the composition tables, after every directory has reserved its
	 * ids and before anything assembles — the same moment, and for the same
	 * reason, as the directories' own equate files.
	 *
	 * <p>One table per composition : a scene count, then three bytes per scene
	 * — its file id and the directory that holds it. The loader needs both :
	 * it mounts a directory before reading the entries of a scene, and a state
	 * spans directories. The scenes are grouped by directory.</p>
	 */
	public static void generate(ImmutableNode layout, BuildContext ctx,
			List<Compositions.Composition> compositions) throws Exception {

		String gen = Attribute.getStringOpt(layout, ctx, "gencompositions");
		if (gen == null || compositions.isEmpty()) {
			return;
		}

		String path = ctx.path + File.separator + gen;
		Files.createDirectories(Paths.get(FileUtil.getDir(path)));
		StringBuilder o = new StringBuilder();
		o.append("* GENERATED by the builder — do not edit").append(System.lineSeparator());
		o.append("* The declared RAM states : the scenes each one holds, with the").append(System.lineSeparator());
		o.append("* directory that carries them. See docs/lang/en/scenes.md.").append(System.lineSeparator());

		for (Compositions.Composition c : compositions) {
			o.append(System.lineSeparator());
			o.append("compositions.").append(c.name).append(System.lineSeparator());
			o.append("        fcb   ").append(c.scenes.size())
			 .append("          ; scenes").append(System.lineSeparator());
			List<Object[]> rows = new ArrayList<Object[]>();
			for (String scene : c.scenes) {
				int[] found = locate(ctx, scene);
				if (found == null) {
					throw new Exception(c.where + ": composition '" + c.name + "' names the scene"
							+ " '" + scene + "', which no <scene> of any directory declares");
				}
				rows.add(new Object[] { scene, found });
			}
			for (Object[] row : byDirectory(rows)) {
				int[] found = (int[]) row[1];
				o.append(String.format("        fdb   %-4d", found[0]))
				 .append("       ; ").append(row[0]).append(System.lineSeparator());
				o.append(String.format("        fcb   %-4d", found[1]))
				 .append("       ;   directory").append(System.lineSeparator());
			}
		}

		FileWriter writer = new FileWriter(path);
		writer.write(o.toString());
		writer.close();
	}

	/**
	 * The scenes grouped by directory, the declaration order kept inside a
	 * group (a stable sort). With one drive, each change of directory between
	 * two disks is a swap the player makes : the loader walks a table in its
	 * order, the directory it has in memory first, so grouped scenes cost one
	 * swap per disk, where an interleaved table asked for disk 1, then 2, then
	 * 1 again (09/10/2026).
	 *
	 * @param rows { scene name, { file id, directory id } }
	 */
	static List<Object[]> byDirectory(List<Object[]> rows) {
		List<Object[]> sorted = new ArrayList<Object[]>(rows);
		sorted.sort((a, b) -> Integer.compare(((int[]) a[1])[1], ((int[]) b[1])[1]));
		return sorted;
	}

	/** @return { file id, directory id } of a scene, null if no directory has it */
	private static int[] locate(BuildContext ctx, String scene) {
		for (Map.Entry<Integer, DirReservations.Reservation> dir
				: ctx.dirReservations.all().entrySet()) {
			int[] idBlocks = dir.getValue().idBlocks.get(scene);
			if (idBlocks != null) {
				return new int[] { idBlocks[0], dir.getKey() };
			}
		}
		return null;
	}
}
