package com.widedot.m6809.gamebuilder.config;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.configuration2.tree.ImmutableNode;

import com.widedot.m6809.gamebuilder.Handlers;
import com.widedot.m6809.gamebuilder.plugin.floppydisk.storage.configuration.Section;
import com.widedot.m6809.gamebuilder.plugin.floppydisk.storage.configuration.Storage;
import com.widedot.m6809.gamebuilder.plugin.floppydisk.storage.configuration.Storages;
import com.widedot.m6809.gamebuilder.spi.BuildContext;
import com.widedot.m6809.gamebuilder.spi.configuration.Attribute;
import com.widedot.m6809.util.FileUtil;

import lombok.extern.slf4j.Slf4j;

/**
 * Collects, from the raw configuration tree, where every {@code <directory>}
 * of the target lives on its media — physical disk, face, track, sector —
 * and writes the table the loader embeds
 * ({@code gen/directories/locations.asm}).
 *
 * <p>The loader keeps ONE directory in memory and reloads another on demand
 * ({@code loader.dir.load}) ; historically the location was a trio of
 * assembly constants, which forced every directory of a game to live at the
 * same spot on its own physical disk. This table lifts that : directories
 * are looked up by id, and the "Insert disk" prompt only fires when the
 * PHYSICAL disk differs from the one currently in the drive. Design :
 * docs/lang/fr/analyse-repertoires-partitionnes-2026-08.md.</p>
 *
 * <p>Pure configuration, like the rest of the placement scan : a directory's
 * spot is its section declaration, the physical disk is the rank of its
 * {@code <floppydisk>} in the target. Nothing here needs the build to have
 * started — which is the point, the loader is assembled long before the
 * directories are emitted.</p>
 */
@Slf4j
public final class DirectoryLocations {

	/** A resolved directory location : physical disk, face, track, sector (0-based). */
	private static final class Row {
		final int disk, face, track, sector;
		final String sectionName;
		Row(int disk, int face, int track, int sector, String sectionName) {
			this.disk = disk; this.face = face; this.track = track;
			this.sector = sector; this.sectionName = sectionName;
		}
	}

	private DirectoryLocations() {
	}

	public static void generate(ImmutableNode targetNode, BuildContext ctx) throws Exception {
		List<Row> rows = new ArrayList<Row>();
		walk(targetNode, ctx.child(), rows, new int[] { 0 });
		if (rows.isEmpty()) {
			return; // no <directory> in this target : nothing consumes the table
		}
		// ids are the table's indexes : they must be dense and start at zero,
		// or the loader would read a hole as a location
		for (int id = 0; id < rows.size(); id++) {
			if (rows.get(id) == null) {
				throw new Exception("directory ids must be contiguous from 0 : id " + id
						+ " is missing while " + (rows.size() - 1) + " exists");
			}
		}

		StringBuilder out = new StringBuilder();
		out.append("* Generated by the builder - do not edit.")
		   .append(System.lineSeparator());
		out.append("* One entry per <directory> of the target, indexed by directory id :")
		   .append(System.lineSeparator());
		out.append("* [physical disk] [face] [track] [sector 0-based]")
		   .append(System.lineSeparator());
		out.append("loader.dir.location.SIZE equ 4").append(System.lineSeparator());
		out.append("loader.dir.count equ ").append(rows.size()).append(System.lineSeparator());
		// a MACRO, not data : this file is included at the top of the loader
		// assembly, BEFORE its org — bytes emitted here would land outside
		// the raw binary (measured at address 0). The loader invokes the
		// macro where its own layout wants the table.
		out.append("_loader.dir.locations.table MACRO").append(System.lineSeparator());
		for (int id = 0; id < rows.size(); id++) {
			Row r = rows.get(id);
			out.append("        fcb   ").append(r.disk).append(',').append(r.face)
			   .append(',').append(r.track).append(',').append(r.sector)
			   .append("   ; directory ").append(id)
			   .append(" (").append(r.sectionName).append(')')
			   .append(System.lineSeparator());
		}
		out.append("        ENDM").append(System.lineSeparator());
		// the loader's current-disk variable starts on the disk that booted :
		// the one holding directory 0
		out.append("loader.dir.bootPhysicalDisk equ ").append(rows.get(0).disk)
		   .append(System.lineSeparator());

		String path = ctx.path + File.separator + "gen" + File.separator
				+ "directories" + File.separator + "locations.asm";
		Files.createDirectories(Paths.get(FileUtil.getDir(path)));
		Files.write(Paths.get(path), out.toString().getBytes());
		log.debug("directory locations table : {} entries -> {}", rows.size(), path);
	}

	/** Walks the tree, replaying defaults/defines like the real pass nests them. */
	private static void walk(ImmutableNode node, BuildContext scope, List<Row> rows,
			int[] diskIndex) throws Exception {
		for (ImmutableNode child : node.getChildren()) {
			String kind = child.getNodeName();
			if ("default".equals(kind) || "define".equals(kind)) {
				Handlers.getDefault(kind).run(child, scope);
				continue;
			}
			if ("floppydisk".equals(kind)) {
				disk(child, scope.child(), rows, diskIndex[0]++);
				continue;
			}
			walk(child, scope, rows, diskIndex);
		}
	}

	private static void disk(ImmutableNode node, BuildContext scope, List<Row> rows,
			int diskIndex) throws Exception {
		String model = Attribute.getString(node, scope, "model");
		String storageFilename = scope.path + Attribute.getString(node, scope, "storage");
		Storage storage = new Storages(storageFilename).get(model);

		for (ImmutableNode child : node.getChildren()) {
			String kind = child.getNodeName();
			if ("default".equals(kind) || "define".equals(kind)) {
				Handlers.getDefault(kind).run(child, scope);
				continue;
			}
			// section overrides apply in document order, as the real pass does
			if ("section".equals(kind)) {
				Section section = new Section(child, scope.defaults);
				storage.sections.put(section.name, section);
				continue;
			}
			if ("directory".equals(kind)) {
				Integer id = Attribute.getInteger(child, scope, "id");
				String sectionName = Attribute.getString(child, scope, "section");
				Section s = storage.sections.get(sectionName);
				if (s == null) {
					throw new Exception(scope.sources.locate(child) + ": directory " + id
							+ " references unknown section '" + sectionName + "'");
				}
				while (rows.size() <= id) {
					rows.add(null);
				}
				if (rows.get(id) != null) {
					throw new Exception(scope.sources.locate(child)
							+ ": directory id " + id + " is declared twice");
				}
				// sections declare sectors 1-based, the loader indexes its
				// interleave list 0-based (DIR_DEFAULT_SECTOR was $04-1)
				rows.set(id, new Row(diskIndex, s.face, s.track, s.sector - 1, sectionName));
				// reserve the directory's file ids and write its gensymbols
				// NOW : the id equates of one directory feed units that live
				// in another (a dependency cycle between title and stages),
				// so every equate file must exist before anything assembles
				com.widedot.m6809.gamebuilder.plugin.directory.DirectoryPlugin
						.reserve(child, scope.child());
			}
		}
	}
}
