---
#this file is a prototype, may migrate from xml to yaml

target:
  name:   fd

  define:   &builder.CHECKMEMORYEXT
    value:  1

  default:  &floppydisk.storage
    value:  new-engine/config/storage.xml

  floppydisk:
    model:  fd640

    data:
      section:  *LOADER
      lwasm:
        format: raw
        file:   new-engine/system/to8/bootloader/loader.asm

    data:
      section:    *BOOT
      maxsize:    0x100
      cksumfd640:
        lwasm:
          format: raw
          file:   new-engine/system/to8/bootloader/boot.asm

    section:  &INDEX
      track:  0
      face:   0
      sector: 14

    section:  &LINK
      track:  0
      face:   1
      sector: 1

    section:  &DATA
      track:  1
      face:   0
      sector: 1

    directory:
      id:       0
      section:  *INDEX
      genBin:   src/directories/directory.bin #optional

      direntries:
          id:           <name>
          section:      *DATA
          linksection:  *LINK
          maxsize:      0x4000
          codec:        zx0
          lwasm:
            format:     obj

      variants:
        properties:
          - name:     assets.main.runpixel
              lwasm:
                file: src/assets/main/run-pixel.asm

          - name:     assets.object.pixel
              lwasm:  
                file: src/assets/object/pixel.asm

          - name:     builder.floppydisk.directory
              genSym: &direntries
                file: src/directories/direntries-id.asm
              lwasm:
                file: *direntries

    output:
      - type: fd
        file: demo.fd

      - type: sd
        file: demo.sd

      - type: sap
        file: demo.sap

      - type: hfe
        file: demo.hfe
...